Repository halide/Halide, pull requests merged in 2020-10, with the labels that each got.

#5298 [d3d12] allocation cache + bugfixes
  python_bindings/correctness/boundary_conditions.py
  src/CodeGen_D3D12Compute_Dev.cpp
  src/runtime/d3d12compute.cpp
  src/runtime/mini_d3d12.h
  src/runtime/windows_d3d12compute_x86.cpp
Labels: backport me

#5321 Add package manager info to README.md
  README.md
Labels: documentation, skip_buildbots

#5308 Fix linking to shared LLVM.
  cmake/BundleStatic.cmake
  dependencies/llvm/CMakeLists.txt
  src/Generator.cpp
Labels: backport me, build

#5330 Fix 32-bit Windows vcvars command
  README.md
Labels: skip_buildbots

#5331 fix bounds inference bug for bounded interval / unbounded interval
  src/Bounds.cpp
Labels: backport me, bug

#5332 Make C++ backend requirement for C++11 explicit (Issue #5311)
  src/CodeGen_C.cpp
Labels: release_notes

#5352 Fix comment for halide_error_code_device_dirty_with_no_device_support
  src/runtime/HalideRuntime.h
Labels: skip_buildbots

#5354 Remove erroneous sentence in comment about GCD
  src/runtime/HalideRuntime.h
Labels: skip_buildbots

#5355 min and max in the algorithm was confusing loop partitioning
  src/PartitionLoops.cpp
  test/correctness/CMakeLists.txt
  test/correctness/partition_max_filter.cpp
Labels: backport me

#5361 Add vcpkg instructions to README.md
  README.md
Labels: documentation, skip_buildbots

#5350 bounds inference (mod) pessimistic on unsigned 0 interval
  src/Bounds.cpp
Labels: enhancement

#5371 Bump version number to 10.0.1
  CMakeLists.txt
  README.md
Labels: skip_buildbots

#5297 OpenCL Texture Support
  Makefile
  python_bindings/src/PyEnums.cpp
  python_bindings/src/PyImageParam.cpp
  src/Closure.h
  src/CodeGen_OpenCL_Dev.cpp
  src/DeviceArgument.cpp
  src/DeviceArgument.h
  src/DeviceInterface.cpp
  src/DeviceInterface.h
  src/Expr.h
  src/FuseGPUThreadLoops.cpp
  src/Generator.h
  src/IRPrinter.cpp
  src/InjectHostDevBufferCopies.cpp
  src/OutputImageParam.cpp
  src/OutputImageParam.h
  src/Parameter.cpp
  src/Parameter.h
  src/StorageFlattening.cpp
  src/runtime/HalideRuntimeOpenCL.h
  src/runtime/cl_functions.h
  src/runtime/opencl.cpp
  src/runtime/runtime_api.cpp
  test/correctness/CMakeLists.txt
  test/correctness/gpu_texture.cpp
  test/generator/CMakeLists.txt
  test/generator/gpu_texture_aottest.cpp
  test/generator/gpu_texture_generator.cpp
Labels: enhancement

#5370 Make loop partitioning a bit more robust for if statements
  src/PartitionLoops.cpp
Labels: enhancement

#5388 Add missing quotes in run-clang-format.sh
  run-clang-format.sh
Labels: backport me, skip_buildbots

#5417 Don't declare round/roundf for multi-threaded MSVC builds (Issue #5403)
  src/CodeGen_C.cpp
Labels: backport me

#5416 Add missing operator^ overloads in CppVector (Issue #5415)
  src/CodeGen_C.cpp
Labels: backport me

#5420 Backport 5419 to 10.0.1
  dependencies/llvm/CMakeLists.txt
Labels: build

#5419 Fix GCC -> GNU in generator expressions
  dependencies/llvm/CMakeLists.txt
Labels: backport me, build
