Repository halide/Halide, pull requests merged in 2020-12, with the labels that each got.

#5507 Restructure apps to be fully external.
  CMakeLists.txt
  apps/CMakeLists.txt
  apps/bgu/CMakeLists.txt
  apps/bilateral_grid/CMakeLists.txt
  apps/blur/CMakeLists.txt
  apps/c_backend/CMakeLists.txt
  apps/camera_pipe/CMakeLists.txt
  apps/conv_layer/CMakeLists.txt
  apps/cuda_mat_mul/CMakeLists.txt
  apps/cuda_mat_mul/runner.cpp
  apps/depthwise_separable_conv/CMakeLists.txt
  apps/harris/CMakeLists.txt
  apps/hist/CMakeLists.txt
  apps/iir_blur/CMakeLists.txt
  apps/interpolate/CMakeLists.txt
  apps/lens_blur/CMakeLists.txt
  apps/linear_algebra/CMakeLists.txt
  apps/linear_algebra/benchmarks/CMakeLists.txt
  apps/linear_algebra/tests/CMakeLists.txt
  apps/local_laplacian/CMakeLists.txt
  apps/max_filter/CMakeLists.txt
  apps/nl_means/CMakeLists.txt
  apps/resize/CMakeLists.txt
  apps/stencil_chain/CMakeLists.txt
  apps/unsharp/CMakeLists.txt
  apps/wavelet/CMakeLists.txt
  cmake/HalideTargetHelpers.cmake
  packaging/CMakeLists.txt
  packaging/HalideConfig.cmake
Labels: apps, build, skip_buildbots

#5506 Add CMake presets for 3.19+ users
  .gitignore
  CMakePresets.json
  README_cmake.md
Labels: build, enhancement, skip_buildbots

#5513 Add version-checking to the clang-tidy and clang-format scripts
  run-clang-format.sh
  run-clang-tidy.sh
Labels: skip_buildbots

#5520 Enable commented clang-format option. Fix schema.
  .clang-format
Labels: code_cleanup, skip_buildbots

#5477 Fixes to bounds inference on shift_left
  src/Bounds.cpp
Labels: bug

#5521 Point fft JIT tests to Halide binary
  apps/fft/CMakeLists.txt
  src/Generator.cpp
Labels: bug, build

#5537 Add code to allow running compare_vs_tflite on Android devices
  apps/interpret_nn/Makefile
  apps/interpret_nn/run_compare_on_device.sh
Labels: skip_buildbots

#5560 Better document how LLVM_DIR works.
  README.md
  README_cmake.md
Labels: documentation, skip_buildbots
