Repository halide/Halide, pull requests merged in 2020-09, with the labels that each got.

#5253 CMake changes to land ahead of releases
  CMakeLists.txt
  apps/CMakeLists.txt
  cmake/HalideTargetHelpers.cmake
  dependencies/wasm/CMakeLists.txt
  doc/CMakeLists.txt
  packaging/CMakeLists.txt
  packaging/HalideConfig.cmake
  packaging/Linux.cmake
  packaging/macOS.cmake
  python_bindings/stub/CMakeLists.txt
  src/CMakeLists.txt
  src/runtime/CMakeLists.txt
  test/correctness/CMakeLists.txt
  test/generator/CMakeLists.txt
  tools/package-linux.sh
  tools/package-macos.zsh
  tools/package-unix.sh
  tools/package-windows.bat
  tools/test-packaging-linux.sh
  tools/test-packaging-macos.zsh
  tutorial/CMakeLists.txt
Labels: build

#5255 Drop static library build from Windows.
  tools/package-windows.bat
Labels: build, skip_buildbots

#5273 fix cmake dir location on Windows
  tools/package-windows.bat
Labels: build, skip_buildbots

#5274 Packaging/fix windows
  tools/package-windows.bat
Labels: build

#5286 Re-enable CUDAVectorize tests.
  test/correctness/atomics.cpp
Labels: backport me

#5295 Rename LINES to INTERESTING_LINES
  tutorial/figures/generate_output_snippets.sh
Labels: skip_buildbots

#5293 [d3d12] recycling "frame" resources and removing superfluous sync points
  src/runtime/d3d12compute.cpp
Labels: backport me

#5216 Replace large code model build option with target feature.
  python_bindings/src/PyEnums.cpp
  src/CMakeLists.txt
  src/CodeGen_Internal.cpp
  src/CodeGen_LLVM.cpp
  src/CodeGen_LLVM.h
  src/Target.cpp
  src/Target.h
  src/runtime/HalideRuntime.h
Labels: build
