Repository halide/Halide, pull requests merged in 2021-05, with the labels that each got.

#5999 Fix Windows apps
  apps/CMakeLists.txt
  cmake/HalideGeneratorHelpers.cmake
Labels: build

#6016 fix package.sh perms
  packaging/tgz/package.sh
Labels: buildbot_test_nothing

#6035 Fix Windows ZIP package script.
  CMakePresets.json
  packaging/CMakeLists.txt
Labels: skip_buildbots

#6034 Update README for Halide 12 release.
  README.md
Labels: skip_buildbots

#6040 Bump Halide version to 13.0.0
  CMakeLists.txt
Labels: skip_buildbots

#6048 Fix tgz/package.sh
  packaging/tgz/package.sh
  packaging/ubuntu/package.sh
Labels: backport me, skip_buildbots

#6047 Don't emit aligned loads to unaligned addresses
  src/CodeGen_LLVM.cpp
  test/correctness/align_bounds.cpp
Labels: backport me, bug

#6051 Backport #6047
  src/CodeGen_LLVM.cpp
  test/correctness/align_bounds.cpp
Labels: skip_buildbots

#6041 Scalar loads/stores shouldn't invalidate predicate vectorization
  src/VectorizeLoops.cpp
  test/correctness/predicated_store_load.cpp
Labels: backport me
