Repository halide/Halide, pull requests merged in 2021-04, with the labels that each got.

#5873 Use fibers to guarantee stack size on Windows
  cmake/HalideTestHelpers.cmake
  src/CodeGen_LLVM.cpp
  src/Lower.cpp
  src/Util.cpp
  src/Util.h
  test/error/CMakeLists.txt
  test/error/run_with_large_stack_throws.cpp
  tutorial/CMakeLists.txt
Labels: release_notes, usability

#5876 Improve ClangCL support by disabling, fixing warnings
  cmake/TargetExportScript.cmake
  src/AssociativeOpsTable.cpp
  src/Buffer.h
  src/CMakeLists.txt
  src/CodeGen_Hexagon.cpp
  src/CodeGen_LLVM.cpp
  src/IRMatch.h
  src/IRVisitor.h
  src/Introspection.cpp
  src/IntrusivePtr.h
  src/LowerWarpShuffles.cpp
  src/Memoization.cpp
  src/ParamMap.h
  src/Schedule.cpp
  src/SelectGPUAPI.cpp
  src/Simplify_Exprs.cpp
  src/StmtToHtml.cpp
  src/Util.cpp
  src/VectorizeLoops.cpp
  src/WasmExecutor.cpp
  src/runtime/HalideBuffer.h
Labels: build

#5885 [cmake] Fix and reorganize warnings for building Halide
  src/CMakeLists.txt
Labels: build

#5887 Require LLD_DIR in zip/package.bat
  tools/package-windows.bat
Labels: skip_buildbots

#5697 [adams2019] Add caching to autoscheduler
  src/autoschedulers/adams2019/AutoSchedule.cpp
  src/autoschedulers/adams2019/CMakeLists.txt
  src/autoschedulers/adams2019/Cache.cpp
  src/autoschedulers/adams2019/Cache.h
  src/autoschedulers/adams2019/Featurization.h
  src/autoschedulers/adams2019/LoopNest.cpp
  src/autoschedulers/adams2019/LoopNest.h
  src/autoschedulers/adams2019/Makefile
  src/autoschedulers/adams2019/State.cpp
  src/autoschedulers/adams2019/State.h
  src/autoschedulers/adams2019/test.cpp
Labels: autoscheduler

#5943 Add support for LSTM to the hannk delegate
  apps/hannk/delegate/hannk_delegate.cpp
  apps/hannk/interpreter/lower.cpp
  apps/hannk/interpreter/lower.h
  apps/hannk/interpreter/ops.cpp
  apps/hannk/tflite/tflite_parser.cpp
Labels: skip_buildbots

#5942 Add support for dynamic tensors to hannk
  apps/hannk/delegate/hannk_delegate.cpp
  apps/hannk/interpreter/model.cpp
  apps/hannk/interpreter/model.h
  apps/hannk/interpreter/ops.cpp
  apps/hannk/interpreter/ops.h
  apps/hannk/interpreter/transforms.cpp
Labels: skip_buildbots
