Repository halide/Halide, pull requests merged in 2021-01, with the labels that each got.

#5592 Add initial support for building a TFLite Delegate
  apps/interpret_nn/Makefile
  apps/interpret_nn/compare_vs_tflite.cpp
  apps/interpret_nn/delegate/exported_symbols.linux
  apps/interpret_nn/delegate/exported_symbols.osx
  apps/interpret_nn/delegate/halide_delegate.cpp
  apps/interpret_nn/delegate/halide_delegate.h
  apps/interpret_nn/delegate/halide_delegate_adaptor.cpp
  apps/interpret_nn/run_compare_on_device.sh
  apps/interpret_nn/tflite/tflite_parser.cpp
Labels: enhancement

#5580 replaced indentation in line 20 with spaces to show proper error message
  Makefile
Labels: code_cleanup

#5583 Use std::unique_ptr to manage CodeGen classes
  src/CodeGen_D3D12Compute_Dev.cpp
  src/CodeGen_D3D12Compute_Dev.h
  src/CodeGen_GPU_Host.cpp
  src/CodeGen_GPU_Host.h
  src/CodeGen_Hexagon.cpp
  src/CodeGen_Hexagon.h
  src/CodeGen_LLVM.cpp
  src/CodeGen_LLVM.h
  src/CodeGen_Metal_Dev.cpp
  src/CodeGen_Metal_Dev.h
  src/CodeGen_OpenCL_Dev.cpp
  src/CodeGen_OpenCL_Dev.h
  src/CodeGen_OpenGLCompute_Dev.cpp
  src/CodeGen_OpenGLCompute_Dev.h
  src/CodeGen_PTX_Dev.cpp
  src/CodeGen_PTX_Dev.h
Labels: code_cleanup

#5623 Fix version to 11.0.0
  CMakeLists.txt
Labels: skip_buildbots

#5553 Prototype of multiple scattering update definitions
  src/Bounds.cpp
  src/CSE.cpp
  src/IR.cpp
  src/IR.h
  src/IROperator.cpp
  src/IROperator.h
  src/Simplify_And.cpp
  src/Simplify_Stmts.cpp
  src/SplitTuples.cpp
  test/correctness/CMakeLists.txt
  test/correctness/multiple_scatter.cpp
Labels: enhancement

#5640 Add 11.1 as an acceptable LLVM version
  Makefile
Labels: backport me

#5644 Upgrade pybind11 to 2.6.x
  python_bindings/CMakeLists.txt
  python_bindings/readme.md
  python_bindings/requirements.txt
  python_bindings/src/CMakeLists.txt
  python_bindings/src/PyHalide.cpp
  python_bindings/stub/PyStubImpl.cpp
Labels: backport me

#5624 Fix cuda warp shuffle issue for narrow types
  src/LowerWarpShuffles.cpp
  test/correctness/register_shuffle.cpp
Labels: bug

#5656 Remove all deprecated methods for Halide 12
  src/BoundaryConditions.h
  src/Dimension.h
  src/Func.cpp
  src/Func.h
  src/Generator.h
  src/Pipeline.cpp
  src/Pipeline.h
Labels: release_notes

#5615 is_positive_const and is_negative_const broken for (some) casts
  src/IROperator.cpp
Labels: bug

#5663 Fix VSX min/max intrinsics. Fixes #5661.
  src/CodeGen_PowerPC.cpp
Labels: backport me

#5675 Fix target detection for i686
  cmake/HalideTargetHelpers.cmake
Labels: backport me, bug
