Repository halide/Halide, pull requests merged in 2021-11, with the labels that each got.

#6365 Use explicit host build strategy for cross compiling HANNK
  CMakeLists.txt
  apps/hannk/.gitignore
  apps/hannk/CMakeLists.txt
  apps/hannk/Makefile
  apps/hannk/configure_cmake.sh
  apps/hannk/halide/CMakeLists.txt
  apps/hannk/util/CMakeLists.txt
  cmake/HalideTargetHelpers.cmake
Labels: buildbot_test_everything

#6378 Update README for Halide 13.
  README.md
Labels: buildbot_test_nothing

#6374 Add super-build for cross-compiling HANNK
  apps/hannk/cmake/superbuild/CMakeLists.txt
  apps/hannk/configure_cmake.sh
Labels: buildbot_test_nothing

#6381 Remove halide_assert() from halide_default_device_wrap_native
  src/runtime/device_interface.cpp
Labels: backport me

#6405 Fix obscure bug in widening let substitution
  src/FindIntrinsics.cpp
  test/correctness/intrinsics.cpp
Labels: bug, backport me
