Repository halide/Halide, pull requests merged in 2021-09, with the labels that each got.

#6233 Upgrade clang-format and clang-tidy to LLVM-12
  .clang-tidy
  .github/workflows/presubmit.yml
  Makefile
  run-clang-format.sh
  run-clang-tidy.sh
Labels: buildbot_test_nothing

#6243 Modify hexagon_remote/Makefile to allow defining C++ #defines on the command line
  src/runtime/hexagon_remote/Makefile
Labels: skip_buildbots

#6257 Usage of C++ `<thread>` header requires linking to threading library
  README.md
  src/CMakeLists.txt
Labels: buildbot_test_everything

#6267 CMake: install docs into halide subdirectory of doc dir
  packaging/CMakeLists.txt
Labels: release_notes
