Repository halide/Halide, pull requests merged in 2021-12, with the labels that each got.

#6491 Document the usage of llvm::legacy::PassManager
  src/CodeGen_PTX_Dev.cpp
  src/LLVM_Output.cpp
Labels: skip_buildbots

#6501 Fix size_t -> int conversion warning
  util/HalideTraceViz.cpp
Labels: skip_buildbots

#6520 Mullapudi2016: don't hardcode the list of supported targets
  src/autoschedulers/mullapudi2016/AutoSchedule.cpp
Labels: autoscheduler, backport me

#6519 Fix weird CMake issue with custom LLVM
  dependencies/llvm/CMakeLists.txt
Labels: bug, build, backport me
