Repository halide/Halide, pull requests merged in 2021-02, with the labels that each got.

#5685 Delete llvm_builder.yml
  .github/workflows/llvm_builder.yml
Labels: skip_buildbots

#5654 [adams2019] Restructure autoscheduler + add timer
  src/autoschedulers/adams2019/AutoSchedule.cpp
  src/autoschedulers/adams2019/CMakeLists.txt
  src/autoschedulers/adams2019/Featurization.h
  src/autoschedulers/adams2019/LoopNest.cpp
  src/autoschedulers/adams2019/LoopNest.h
  src/autoschedulers/adams2019/Makefile
  src/autoschedulers/adams2019/State.cpp
  src/autoschedulers/adams2019/State.h
  src/autoschedulers/adams2019/Timer.h
Labels: autoscheduler

#5618 Add fixes to overflow analysis in bounds inference
  src/Bounds.cpp
  src/Type.h
Labels: bug

#5745 Fix subsetted build issues with arm32/64, hexagon.
  src/CodeGen_Hexagon.cpp
  src/LLVM_Runtime_Linker.cpp
  src/runtime/CMakeLists.txt
Labels: backport me

#5761 Constrain calling convention for PyStub
  python_bindings/correctness/pystub.py
  python_bindings/stub/PyStubImpl.cpp
Labels: release_notes
