Repository halide/Halide, pull requests merged in 2021-08, with the labels that each got.

#6155 Add more fine-grained prefetch() directive (Issue #3735)
  apps/blur/halide_blur_generator.cpp
  apps/camera_pipe/camera_pipe_generator.cpp
  python_bindings/src/PyScheduleMethods.h
  src/CodeGen_Hexagon.cpp
  src/Func.cpp
  src/Func.h
  src/Prefetch.cpp
  src/PrefetchDirective.h
  src/SlidingWindow.cpp
  src/runtime/prefetch.cpp
  src/runtime/qurt_hvx.cpp
  test/correctness/prefetch.cpp
Labels: release_notes

#6161 Update tutorial todos
  tutorial/todo.txt
Labels: skip_buildbots

#6196 Add information to comment on ```align_loads```.
  src/AlignLoads.h
Labels: skip_buildbots

#6200 Fix unroll failures from adams2019 when the Expr depends on estimates
  src/autoschedulers/adams2019/FunctionDAG.cpp
  src/autoschedulers/adams2019/FunctionDAG.h
Labels: autoscheduler
