Repository halide/Halide, pull requests merged in 2022-05, with the labels that each got.

#6743 Add __pycache__ to toplevel .gitignore file
  .gitignore
Labels: skip_buildbots

#6749 Update hannk README link to hosted models page
  apps/hannk/README.md
Labels: skip_buildbots

#6754 Deprecate disable_llvm_loop_opt (#4113)
  apps/onnx/model.cpp
  python_bindings/src/PyEnums.cpp
  src/CodeGen_LLVM.cpp
  src/CodeGen_PTX_Dev.cpp
  src/HexagonOffload.cpp
  src/Target.cpp
  src/Target.h
  src/autoschedulers/adams2019/autotune_loop.sh
  src/runtime/HalideRuntime.h
  test/correctness/simd_op_check.h
  test/performance/const_division.cpp
  test/performance/nested_vectorization_gemm.cpp
Labels: release_notes

#6772 Add Func::type()/types(), deprecate Func::output_type()/output_types()
  apps/fft/fft.cpp
  python_bindings/correctness/basics.py
  python_bindings/correctness/generators/complex_generator.cpp
  python_bindings/src/PyFunc.cpp
  python_bindings/tutorial/lesson_14_types.py
  src/Func.cpp
  src/Func.h
  src/Generator.cpp
  src/Generator.h
  test/correctness/typed_func.cpp
  test/generator/stubtest_generator.cpp
  tutorial/lesson_15_generators.cpp
Labels: release_notes

#6774 Fix annoying typo in Func.h
  src/Func.h
Labels: skip_buildbots

#6785 LLVM codegen: register AA pipeline if LLVM is older than 14
  src/CodeGen_LLVM.cpp
Labels: buildbot_test_everything
