Repository halide/Halide, pull requests merged in 2022-07, with the labels that each got.

#6842 Check RDom::where predicates for race conditions
  .gitignore
  src/ParallelRVar.cpp
  test/correctness/CMakeLists.txt
  test/correctness/reduction_predicate_racing.cpp
  test/error/CMakeLists.txt
  test/error/rdom_where_races.cpp
Labels: bug

#6844 Deprecate/remove Generator::get_externs_map() and friends
  src/AbstractGenerator.cpp
  src/AbstractGenerator.h
  src/CodeGen_C.cpp
  src/CodeGen_LLVM.cpp
  src/CodeGen_LLVM.h
  src/ExternalCode.h
  src/Generator.cpp
  src/Generator.h
  src/Module.cpp
  src/Module.h
  src/Pipeline.h
  test/correctness/CMakeLists.txt
  test/correctness/external_code.cpp
  test/generator/CMakeLists.txt
  test/generator/abstractgeneratortest_generator.cpp
  test/generator/external_code_aottest.cpp
  test/generator/external_code_extern.cpp
  test/generator/external_code_generator.cpp
Labels: release_notes

#6866 [Codegen_LLVM] Define all the things
  src/CodeGen_Hexagon.cpp
  src/CodeGen_LLVM.cpp
  src/CodeGen_LLVM.h
  src/runtime/aarch64.ll
  src/runtime/arm.ll
  src/runtime/powerpc.ll
  src/runtime/wasm_math.ll
  src/runtime/x86.ll
  src/runtime/x86_avx2.ll
  src/runtime/x86_avx512.ll
  src/runtime/x86_sse41.ll
Labels: buildbot_test_everything

#6869 Add set-host-dirty/copy-to-host to PythonExtensionGen
  src/PythonExtensionGen.cpp
Labels: release_notes

#6861 Remove (most) of the env var usage from Adams2019
  src/Pipeline.cpp
  src/autoschedulers/adams2019/AutoSchedule.cpp
  src/autoschedulers/adams2019/Cache.cpp
  src/autoschedulers/adams2019/Cache.h
  src/autoschedulers/adams2019/CostModel.h
  src/autoschedulers/adams2019/LoopNest.cpp
  src/autoschedulers/adams2019/LoopNest.h
  src/autoschedulers/adams2019/Makefile
  src/autoschedulers/adams2019/State.cpp
  src/autoschedulers/adams2019/State.h
  src/autoschedulers/adams2019/autotune_loop.sh
  src/autoschedulers/adams2019/test.cpp
Labels: release_notes, buildbot_test_everything
