Repository halide/Halide, pull requests merged in 2022-10, with the labels that each got.

#6938 Add pip packaging workflow to GHA
  .github/workflows/pip.yml
  MANIFEST.in
  packaging/CMakeLists.txt
  pyproject.toml
  python_bindings/requirements.txt
  python_bindings/setup.py
  requirements.txt
  setup.py
  src/autoschedulers/adams2019/CMakeLists.txt
Labels: skip_buildbots, buildbot_test_nothing

#7091 Update README.md
  README.md
Labels: buildbot_test_nothing

#7092 Update README.md (#7091)
  README.md
Labels: buildbot_test_nothing

#7097 Update pip.yml to use LLVM 15.0.2
  .github/workflows/pip.yml
Labels: backport me, buildbot_test_nothing

#7103 Fix subtle CMake Install bugs
  CMakeLists.txt
Labels: backport me

#7107 Fix some dead links to the 'master' branch
  README_cmake.md
  README_python.md
  apps/bgu/bgu_generator.cpp
  python_bindings/test/correctness/extern.py
  tutorial/lesson_11_cross_compilation.cpp
Labels: backport me

#7098 Attempt to fix pip build issues
  .github/workflows/pip.yml
  setup.py
Labels: skip_buildbots, buildbot_test_nothing

#7108 Add evaluate() and evaluate_may_gpu() to Python bindings
  python_bindings/src/halide/halide_/PyBuffer.cpp
  python_bindings/src/halide/halide_/PyBuffer.h
  python_bindings/src/halide/halide_/PyFunc.cpp
  python_bindings/src/halide/halide_/PyTuple.cpp
  python_bindings/src/halide/halide_/PyTuple.h
  python_bindings/test/correctness/division.py
Labels: backport me

#7117 Require Python 3.8+ in CMake build
  python_bindings/CMakeLists.txt
Labels: backport me

#7127 add 'reverse_axes' options to Buffer conversions
  python_bindings/src/halide/halide_/PyBuffer.cpp
  python_bindings/src/halide/halide_/PyBuffer.h
  python_bindings/src/halide/halide_/PyCallable.cpp
  python_bindings/test/correctness/buffer.py
Labels: backport me, release_notes, python

#7125 Fix Python buffer handling
  python_bindings/src/halide/CMakeLists.txt
  python_bindings/src/halide/halide_/PyBuffer.cpp
  python_bindings/src/halide/halide_/PyBuffer.h
  python_bindings/src/halide/halide_/PyCallable.cpp
  python_bindings/src/halide/imageio.py
  python_bindings/test/apps/bilateral_grid_shell.py
  python_bindings/test/apps/blur.py
  python_bindings/test/apps/erode.py
  python_bindings/test/apps/interpolate.py
  python_bindings/test/apps/local_laplacian.py
  python_bindings/test/correctness/buffer.py
  python_bindings/tutorial/lesson_02_input_image.py
  python_bindings/tutorial/lesson_07_multi_stage_pipelines.py
  python_bindings/tutorial/lesson_09_update_definitions.py
  python_bindings/tutorial/lesson_12_using_the_gpu.py
Labels: backport me, release_notes, python

#7137 halide.imageio needs to support arbitrary bufferviews
  python_bindings/src/halide/imageio.py
Labels: backport me, python

#7133 Rewrite python_bindings/apps
  python_bindings/src/halide/__init__.py
  python_bindings/src/halide/_generator_helpers.py
  python_bindings/test/apps/CMakeLists.txt
  python_bindings/test/apps/bilateral_grid_app.py
  python_bindings/test/apps/bilateral_grid_generator.py
  python_bindings/test/apps/blur.py
  python_bindings/test/apps/blur_app.py
  python_bindings/test/apps/blur_generator.py
  python_bindings/test/apps/erode.py
  python_bindings/test/apps/interpolate.py
  python_bindings/test/apps/interpolate_app.py
  python_bindings/test/apps/interpolate_generator.py
  python_bindings/test/apps/local_laplacian.py
  python_bindings/test/apps/local_laplacian_app.py
  python_bindings/test/apps/local_laplacian_generator.py
  python_bindings/test/generators/CMakeLists.txt
  python_bindings/test/generators/bilateral_grid_generator.py
Labels: backport me, python
