Repository halide/Halide, pull requests merged in 2022-06, with the labels that each got.

#6795 Add missing include to test_sharding.h
  test/common/test_sharding.h
Labels: skip_buildbots

#6824 Update presets to format version 3
  CMakePresets.json
  README_cmake.md
Labels: skip_buildbots, buildbot_test_nothing

#6777 Add a new, alternate JIT-call convention
  Makefile
  python_bindings/correctness/CMakeLists.txt
  python_bindings/correctness/buffer.py
  python_bindings/correctness/callable.py
  python_bindings/src/CMakeLists.txt
  python_bindings/src/PyBuffer.cpp
  python_bindings/src/PyBuffer.h
  python_bindings/src/PyCallable.cpp
  python_bindings/src/PyCallable.h
  python_bindings/src/PyFunc.cpp
  python_bindings/src/PyHalide.cpp
  python_bindings/src/PyParam.cpp
  python_bindings/src/PyPipeline.cpp
  python_bindings/stub/PyStubImpl.cpp
  src/AbstractGenerator.cpp
  src/AbstractGenerator.h
  src/CMakeLists.txt
  src/Callable.cpp
  src/Callable.h
  src/Func.cpp
  src/Func.h
  src/Generator.cpp
  src/Generator.h
  src/JITModule.cpp
  src/JITModule.h
  src/Pipeline.cpp
  src/Pipeline.h
  src/WasmExecutor.cpp
  src/WasmExecutor.h
  src/runtime/HalideRuntime.h
  test/correctness/CMakeLists.txt
  test/correctness/callable.cpp
  test/correctness/callable_errors.cpp
  test/correctness/callable_generator.cpp
  test/correctness/callable_typed.cpp
  test/error/CMakeLists.txt
  test/error/callable_bad_arguments.cpp
  test/error/callable_bad_values_passed.cpp
  test/error/callable_typed_bad_arguments.cpp
  test/error/callable_typed_bad_arguments_buffer_dims.cpp
  test/error/callable_typed_bad_arguments_buffer_type.cpp
  test/generator/configure_jittest.cpp
  test/generator/example_jittest.cpp
  test/generator/stubtest_jittest.cpp
Labels: release_notes

#6833 Scrub Python from Makefile after buildbot update
  Makefile
Labels: skip_buildbots, buildbot_test_nothing
