Repository halide/Halide, pull requests merged in 2022-01, with the labels that each got.

#6511 free shape storage last
  src/runtime/HalideBuffer.h
Labels: backport me

#6516 [NFC-ish] Finish MSAN handling (Refs. #6513)
  src/CodeGen_LLVM.cpp
Labels: code_cleanup

#6517 Implement SanitizerCoverage support (Refs. #6513)
  Makefile
  python_bindings/src/PyEnums.cpp
  src/CodeGen_LLVM.cpp
  src/LLVM_Headers.h
  src/Module.cpp
  src/Target.cpp
  src/Target.h
  src/runtime/HalideRuntime.h
  test/generator/CMakeLists.txt
  test/generator/sanitizercoverage_aottest.cpp
  test/generator/sanitizercoverage_generator.cpp
Labels: enhancement, usability, release_notes

#6530 Install Python tutorials
  packaging/CMakeLists.txt
Labels: backport me

#6525 Fix Python GIL lock handling (Fixes #6524, Fixes #5631)
  python_bindings/src/PyError.cpp
  python_bindings/src/PyFunc.cpp
  python_bindings/src/PyPipeline.cpp
  src/PythonExtensionGen.cpp
Labels: backport me

#6523 If cmake built a python module, teach cmake to install the python module
  packaging/CMakeLists.txt
Labels: backport me

#6537 Remove unnecessary `std::move` calls
  python_bindings/src/PyFunc.cpp
  python_bindings/src/PyPipeline.cpp
Labels: backport me

#6534 Allow third parties to externally override SOVERSION
  src/CMakeLists.txt
Labels: build, backport me

#6570 Fix typo in comment in HalideBuffer.h
  src/runtime/HalideBuffer.h
Labels: skip_buildbots

#6574 Expand optional static-typing for Buffer to include dimensionality
  apps/fft/fft_aot_test.cpp
  apps/hannk/util/buffer_util.h
  python_bindings/src/PyBuffer.cpp
  src/Argument.h
  src/Buffer.h
  src/Closure.h
  src/Generator.cpp
  src/Generator.h
  src/Module.h
  src/Parameter.h
  src/RDom.h
  src/Realization.h
  src/runtime/HalideBuffer.h
  test/correctness/halide_buffer.cpp
  test/generator/metadata_tester_generator.cpp
  tools/halide_image_io.h
Labels: enhancement, release_notes
