Repository halide/Halide, pull requests merged in 2022-08, with the labels that each got.

#6897 [Codegen_LLVM] Annotate LLVM IR functions with `nounwind`/`mustprogress` attributes
  src/CodeGen_Internal.cpp
  src/CodeGen_LLVM.cpp
Labels: buildbot_test_everything

#6906 Fix broken Makefile rules for autoschedulers on OSX
  Makefile
  apps/support/Makefile.inc
  src/autoschedulers/adams2019/Makefile
  src/autoschedulers/adams2019/autotune_loop.sh
  src/autoschedulers/li2018/Makefile
  src/autoschedulers/mullapudi2016/Makefile
Labels: buildbot_test_everything

#6886 Pip packaging new attempt
  .gitignore
  CMakeLists.txt
  cmake/FindHalide.cmake
  packaging/CMakeLists.txt
  python_bindings/CMakeLists.txt
  python_bindings/pyproject.toml
  python_bindings/setup.py
  python_bindings/src/halide/CMakeLists.txt
  python_bindings/tutorial/CMakeLists.txt
Labels: buildbot_test_everything

#6912 LICENSE.txt: Include full text of Apache 2.0 license (not just the 'header' version)
  LICENSE.txt
Labels: skip_buildbots

#6913 LICENSE.txt: add spirv license
  LICENSE.txt
Labels: skip_buildbots

#6914 LICENSE.txt: add BLAS license.
  LICENSE.txt
Labels: skip_buildbots

#6927 Halide::Error should not extend std::runtime_error
  src/Error.cpp
  src/Error.h
  src/Generator.cpp
Labels: release_notes

#6934 Add build & test presets for release and debug CMake builds
  CMakePresets.json
Labels: skip_buildbots

#6936 Fix badly-merged CMakePresets.json file
  CMakePresets.json
Labels: skip_buildbots

#6939 Add/update Python Readme
  README_python.md
  python_bindings/readme.md
  python_bindings/todo.txt
Labels: skip_buildbots

#6958 Fix RPATH for Python wheels on macOS
  python_bindings/setup.py
Labels: skip_buildbots

#6968 Use CMake target to handle vendored SPIRV headers
  dependencies/spirv/CMakeLists.txt
  src/CMakeLists.txt
Labels: skip_buildbots

#6977 Fix XCode by wrapping weights in an OBJECT library
  src/autoschedulers/adams2019/CMakeLists.txt
Labels: skip_buildbots

#6983 Add test for _Halide_target_export_single_symbol
  python_bindings/test/generators/CMakeLists.txt
Labels: buildbot_test_everything

#6985 Add `add_halide_runtime` rule
  README_cmake.md
  README_python.md
  cmake/HalideGeneratorHelpers.cmake
  python_bindings/test/generators/CMakeLists.txt
Labels: release_notes

#6988 Fix markdown links
  README_cmake.md
Labels: skip_buildbots

#6986 Improve error-handling in Python Extensions
  python_bindings/test/correctness/multi_method_module_test.py
  src/PythonExtensionGen.cpp
Labels: release_notes, python
