Repository halide/Halide, pull requests merged in 2023-04, with the labels that each got.

#7472 Port #6869 to PyCallable (Fix #7213)
  python_bindings/CMakeLists.txt
  python_bindings/src/halide/halide_/PyCallable.cpp
Labels: backport me, release_notes

#7475 Use static dimensions in autoscheduler test generators
  test/autoschedulers/adams2019/demo_generator.cpp
  test/autoschedulers/adams2019/included_schedule_file_generator.cpp
  test/autoschedulers/anderson2021/demo_generator.cpp
  test/autoschedulers/anderson2021/included_schedule_file_generator.cpp
Labels: buildbot_test_everything

#7480 Bump version to 15.0.1
  CMakeLists.txt
Labels: skip_buildbots

#7479 Turn on WITH_UTILS in CMakePresets.json for 'package' preset (Fixes #7465)
  CMakePresets.json
Labels: skip_buildbots, backport me

#7494 fix python binding method export
  python_bindings/src/halide/__init__.py
  python_bindings/src/halide/halide_/PyImageParam.cpp
Labels: backport me, buildbot_test_everything

#7421 Feature Enhancement: Halide IR HTML Visualization
  Makefile
  src/CMakeLists.txt
  src/CodeGen_LLVM.cpp
  src/CodeGen_LLVM.h
  src/Generator.cpp
  src/Module.cpp
  src/Module.h
  src/StmtToViz.cpp
  src/StmtToViz.h
  src/irvisualizer/StmtToViz_dependencies.template.html
  src/irvisualizer/StmtToViz_javascript.template.html
  src/irvisualizer/StmtToViz_stylesheet.template.html
Labels: enhancement

#7357 Deprecate ParamMap (#7121)
  src/Func.h
  src/ParamMap.h
  test/correctness/param_map.cpp
  test/performance/CMakeLists.txt
  test/performance/thread_safe_jit_callable.cpp
  test/performance/thread_safe_jit_param_map.cpp
Labels: release_notes

#7525 Use a find-module to locate Dawn/WebGPU
  cmake/FindHalide_WebGPU.cmake
  cmake/HalideGeneratorHelpers.cmake
  packaging/CMakeLists.txt
  src/CodeGen_WebGPU_Dev.cpp
Labels: buildbot_test_everything

#7505 metal : replacing `arg_sizes` by `arg_types` in kernel run interface
  src/CodeGen_Metal_Dev.cpp
  src/runtime/HalideRuntimeMetal.h
  src/runtime/metal.cpp
Labels: code_cleanup
