Repository halide/Halide, pull requests merged in 2023-06, with the labels that each got.

#7602 Disable fuzzer when using ASAN
  cmake/toolchain.linux-x64-asan.cmake
Labels: skip_buildbots

#7566 Adds fuzzing preset
  CMakePresets.json
  README.md
  README_fuzz_testing.md
  cmake/HalideTestHelpers.cmake
  cmake/toolchain.linux-x64-fuzzer.cmake
  test/fuzz/CMakeLists.txt
Labels: release_notes

#7610 Update Compiler/OS versions in README
  README.md
Labels: skip_buildbots, release_notes

#7626 Fix inverted may_subtile checks
  src/autoschedulers/adams2019/LoopNest.cpp
Labels: autoscheduler, backport me, release_notes

#7627 Deprecate OpenGLCompute for Halide 16
  src/JITModule.cpp
  src/Module.cpp
  src/Pipeline.cpp
  src/Target.h
  src/runtime/HalideRuntime.h
  src/runtime/HalideRuntimeOpenGLCompute.h
  src/runtime/openglcompute.cpp
Labels: release_notes

#7604 Get the ASAN toolchain working again
  README_cmake.md
  cmake/HalideGeneratorHelpers.cmake
  cmake/toolchain.linux-x64-asan.cmake
  python_bindings/CMakeLists.txt
  python_bindings/src/halide/CMakeLists.txt
  src/autoschedulers/anderson2021/CMakeLists.txt
  test/autoschedulers/li2018/CMakeLists.txt
Labels: release_notes

#7658 Dependency wrangling part 0/N: standard CMake modules
  CMakeLists.txt
  dependencies/CMakeLists.txt
  dependencies/jpeg/CMakeLists.txt
  dependencies/png/CMakeLists.txt
  tools/CMakeLists.txt
  tutorial/CMakeLists.txt
Labels: build, code_cleanup, buildbot_test_everything
