Repository halide/Halide, pull requests merged in 2023-01, with the labels that each got.

#7266 Update README_python.md
  README_python.md
Labels: skip_buildbots

#7274 Add CMake support for C++ backend in test/generator
  Makefile
  src/CodeGen_C.cpp
  test/generator/CMakeLists.txt
Labels: release_notes

#7289 Drop support for MIPS (#7287)
  .github/workflows/pip.yml
  Makefile
  README.md
  README_cmake.md
  README_webassembly.md
  apps/HelloAndroid/README.md
  apps/HelloAndroid/build.gradle
  apps/HelloAndroid/build.sh
  apps/HelloAndroid/jni/Application.mk
  apps/HelloAndroidCamera2/README.md
  apps/HelloAndroidCamera2/build.gradle
  apps/HelloAndroidCamera2/build.sh
  apps/HelloAndroidCamera2/jni/Application.mk
  apps/openglcompute/jni/Application.mk
  cmake/HalideTargetHelpers.cmake
  dependencies/llvm/CMakeLists.txt
  packaging/common/Description.txt
  python_bindings/src/halide/halide_/PyEnums.cpp
  src/CMakeLists.txt
  src/CodeGen_LLVM.cpp
  src/CodeGen_MIPS.cpp
  src/CodeGen_PowerPC.cpp
  src/CodeGen_RISCV.cpp
  src/CodeGen_Targets.h
  src/LLVM_Runtime_Linker.cpp
  src/Target.cpp
  src/Target.h
  src/runtime/CMakeLists.txt
  src/runtime/mips.ll
  src/runtime/mips_cpu_features.cpp
Labels: release_notes

#7279 [HVX] Fix EliminateInterleaves
  src/HexagonOptimize.cpp
Labels: performance, hexagon

#7280 [x86 & wasm] Split up double saturating-narrows from i32
  src/CodeGen_WebAssembly.cpp
  src/CodeGen_X86.cpp
  test/correctness/simd_op_check_wasm.cpp
  test/correctness/simd_op_check_x86.cpp
Labels: performance
