Repository halide/Halide, pull requests merged in 2024-08, with the labels that each got.

#8367 Distribute GenGen as a static library
  apps/hexagon_benchmarks/CMakeLists.txt
  cmake/HalideGeneratorHelpers.cmake
  cmake/MutexCopy.ps1
  packaging/CMakeLists.txt
  tools/CMakeLists.txt
Labels: release_notes

#8373 Use a Find module for V8
  README_webassembly.md
  cmake/FindV8.cmake
  dependencies/wasm/CMakeLists.txt
  src/CMakeLists.txt
Labels: release_notes

#8374 Use a Find module for NodeJS
  cmake/FindNodeJS.cmake
  dependencies/wasm/CMakeLists.txt
Labels: release_notes

#8377 Move dependencies/wasm to use sites
  CMakeLists.txt
  README_cmake.md
  dependencies/CMakeLists.txt
  dependencies/wasm/CMakeLists.txt
  src/CMakeLists.txt
  test/generator/CMakeLists.txt
Labels: release_notes

#8378 Replace FetchContent with a custom dependency provider
  CMakeLists.txt
  cmake/dependencies.cmake
  packaging/CMakeLists.txt
  python_bindings/CMakeLists.txt
  src/CMakeLists.txt
Labels: release_notes

#8371 Two more build fixes
  src/runtime/HalideRuntime.h
  test/integration/CMakeLists.txt
Labels: buildbot_test_everything

#8381 Fix Numpy 2.0 compatibility bug in lesson 10
  python_bindings/tutorial/lesson_10_aot_compilation_run.py
Labels: bug

#8379 Rework LLVM into Find module and enact new component policy.
  CMakeLists.txt
  CMakePresets.json
  README_cmake.md
  cmake/FindHalide_LLVM.cmake
  dependencies/README.md
  dependencies/llvm/CMakeLists.txt
  packaging/CMakeLists.txt
  python_bindings/apps/CMakeLists.txt
  python_bindings/test/CMakeLists.txt
  python_bindings/test/correctness/CMakeLists.txt
  python_bindings/tutorial/CMakeLists.txt
  run-clang-tidy.sh
  src/CMakeLists.txt
  src/runtime/CMakeLists.txt
  test/autoschedulers/CMakeLists.txt
  test/autoschedulers/li2018/CMakeLists.txt
  test/generator/CMakeLists.txt
  tutorial/CMakeLists.txt
Labels: release_notes

#8386 Rewrite bundle_static to be much more efficient.
  CMakeLists.txt
  CMakePresets.json
  README_cmake.md
  cmake/BundleStatic.cmake
  src/CMakeLists.txt
Labels: release_notes

#8387 Support using vcpkg to build dependencies on all platforms
  .gitignore
  CMakeLists.txt
  CMakePresets.json
  cmake/vcpkg/llvm/portfile.cmake
  cmake/vcpkg/llvm/vcpkg.json
  cmake/vcpkg/python3/portfile.cmake
  cmake/vcpkg/python3/vcpkg.json
  vcpkg.json
Labels: release_notes

#8392 Fix bundling error on buildbots
  cmake/BundleStatic.cmake
Labels: buildbot_test_nothing
