Repository halide/Halide, pull requests merged in 2024-12, with the labels that each got.

#8495 Fix Apple libtool detection in bundle_static
  cmake/BundleStatic.cmake
Labels: skip_buildbots, buildbot_test_nothing

#8433 Don't spin on the main mutex while waiting for new work
  src/runtime/synchronization_common.h
  src/runtime/thread_pool_common.h
Labels: dev_meeting

#8500 Fix comment for Buffer::copy() (Fixes #8498)
  src/runtime/HalideBuffer.h
Labels: buildbot_test_nothing

#8524 Fix Debian packaging
  .github/workflows/pip.yml
  cmake/HalidePackageConfigHelpers.cmake
  src/CMakeLists.txt
Labels: backport me

#8540 Use a consistent idiom for visit_let
  src/BoundSmallAllocations.cpp
  src/ClampUnsafeAccesses.cpp
  src/Deinterleave.cpp
  src/EliminateBoolVectors.cpp
  src/FuseGPUThreadLoops.cpp
  src/HexagonOptimize.cpp
  src/LICM.cpp
  src/LowerWarpShuffles.cpp
  src/OptimizeShuffles.cpp
  src/RemoveUndef.cpp
  src/SimplifyCorrelatedDifferences.cpp
  src/TrimNoOps.cpp
  src/UniquifyVariableNames.cpp
  src/VectorizeLoops.cpp
Labels: code_cleanup

#8539 Fix UB-introducing rewrite in FindIntrinsics
  src/FindIntrinsics.cpp
  src/IROperator.cpp
  src/IROperator.h
  test/correctness/intrinsics.cpp
Labels: bug
