Repository halide/Halide, pull requests merged in 2024-06, with the labels that each got.

#8260 Fix Metal handling for float16 literals
  src/CodeGen_Metal_Dev.cpp
  test/correctness/CMakeLists.txt
  test/correctness/gpu_f16_intrinsics.cpp
Labels: release_notes

#8259 [vulkan] Fix Vulkan SIMT mappings for GPU loop vars.
  src/CodeGen_C.cpp
  src/CodeGen_Vulkan_Dev.cpp
Labels: bug

#8187 [Hexagon] Profiling changes for abadams/per_instance_profiling
  src/Profiling.cpp
  src/runtime/hexagon_host.cpp
  src/runtime/hexagon_remote/bin/host/libhalide_hexagon_host.so
  src/runtime/hexagon_remote/bin/v65/hexagon_sim_remote
  src/runtime/hexagon_remote/bin/v65/libhalide_hexagon_remote_skel.so
  src/runtime/hexagon_remote/bin/v65/libsim_qurt.a
  src/runtime/hexagon_remote/bin/v65/signed_by_debug/libhalide_hexagon_remote_skel.so
  src/runtime/hexagon_remote/qurt/known_symbols.cpp
  src/runtime/hexagon_remote/qurt/sim_remote.cpp
Labels: buildbot_test_hvx

#8240 No longer silently hide errors in Metal completion handlers (alternative approach)
  src/runtime/HalideRuntimeMetal.h
  src/runtime/metal.cpp
  test/correctness/CMakeLists.txt
  test/correctness/gpu_metal_completion_handler_error_check.cpp
  test/generator/CMakeLists.txt
  test/generator/metal_completion_handler_override_aottest.cpp
  test/generator/metal_completion_handler_override_generator.cpp
Labels: gpu

#8289 [vulkan] Dynamically load Vulkan loader library. Avoid Validation Layer crash on exit.
  Makefile
  README_vulkan.md
  cmake/HalideGeneratorHelpers.cmake
  src/runtime/mini_vulkan.h
  src/runtime/vulkan.cpp
  src/runtime/vulkan_context.h
  src/runtime/vulkan_functions.h
  src/runtime/vulkan_interface.h
  src/runtime/vulkan_internal.h
  src/runtime/vulkan_memory.h
  src/runtime/vulkan_resources.h
  test/correctness/gpu_object_lifetime_1.cpp
  test/correctness/gpu_object_lifetime_2.cpp
  test/correctness/gpu_object_lifetime_3.cpp
  test/correctness/leak_device_memory.cpp
  test/generator/gpu_object_lifetime_aottest.cpp
Labels: bug, dev_meeting

#8273 Remove Introspection
  Makefile
  python_bindings/src/halide/halide_/PyScheduleMethods.h
  src/Buffer.h
  src/CMakeLists.txt
  src/Definition.cpp
  src/Definition.h
  src/Deserialization.cpp
  src/Error.cpp
  src/Func.cpp
  src/Func.h
  src/Generator.cpp
  src/Generator.h
  src/ImageParam.cpp
  src/Introspection.cpp
  src/Introspection.h
  src/ObjectInstanceRegistry.cpp
  src/ObjectInstanceRegistry.h
  src/Param.h
  src/RDom.cpp
  src/RDom.h
  src/Serialization.cpp
  src/Util.cpp
  src/Util.h
  src/Var.cpp
  test/correctness/CMakeLists.txt
  test/correctness/introspection.cpp
Labels: release_notes

#8153 Per-pipeline-invocation profiling
  src/BoundsInference.cpp
  src/CodeGen_Internal.cpp
  src/IR.cpp
  src/IR.h
  src/Profiling.cpp
  src/Profiling.h
  src/runtime/HalideRuntime.h
  src/runtime/fuchsia_clock.cpp
  src/runtime/hexagon_host.cpp
  src/runtime/hexagon_remote/bin/host/libhalide_hexagon_host.so
  src/runtime/hexagon_remote/bin/v65/hexagon_sim_remote
  src/runtime/hexagon_remote/bin/v65/libhalide_hexagon_remote_skel.so
  src/runtime/hexagon_remote/bin/v65/libsim_qurt.a
  src/runtime/hexagon_remote/bin/v65/signed_by_debug/libhalide_hexagon_remote_skel.so
  src/runtime/hexagon_remote/qurt/halide_remote.cpp
  src/runtime/hexagon_remote/qurt/known_symbols.cpp
  src/runtime/hexagon_remote/qurt/sim_remote.cpp
  src/runtime/linux_clock.cpp
  src/runtime/osx_clock.cpp
  src/runtime/posix_clock.cpp
  src/runtime/posix_timer_profiler.cpp
  src/runtime/profiler_common.cpp
  src/runtime/profiler_inlined.cpp
  src/runtime/runtime_api.cpp
  src/runtime/runtime_atomics.h
  src/runtime/runtime_internal.h
  src/runtime/windows_clock.cpp
Labels: release_notes, dev_meeting

#8321 Remove deprecated operators
  python_bindings/src/halide/halide_/PyIROperator.cpp
  src/IROperator.h
Labels: release_notes

#8325 Correct the Halide version number in setup.py
  setup.py
Labels: skip_buildbots
