Repository halide/Halide, pull requests merged in 2025-08, with the labels that each got.

#8705 Fix WASM splat op check test.
  src/LLVM_Runtime_Linker.cpp
  test/correctness/simd_op_check_wasm.cpp
Labels: error_message

#8710 Use AArch64 assembly syntax on macOS with LLVM<22
  src/CodeGen_Internal.cpp
  src/LLVM_Output.cpp
Labels: usability

#8748 fix(stmt-html): Fix embedded Buffer processing performance issue.
  src/Bounds.cpp
  src/CompilerLogger.cpp
  src/Module.cpp
  src/StmtToHTML.cpp
  src/Target.cpp
  src/Util.cpp
  src/Util.h
  test/correctness/pytorch.cpp
Labels: performance, code_cleanup

#8674 Fix rewrite that doesn't preserve type
  src/FindIntrinsics.cpp
Labels: dev_meeting

#8775 Prefer to build against libjpeg-turbo and document this.
  CMakePresets.json
  Makefile
  apps/support/Makefile.inc
  doc/BuildingHalideWithCMake.md
Labels: build
