Repository halide/Halide, pull requests merged in 2025-05, with the labels that each got.

#8612 AMD Zen5 support
  python_bindings/src/halide/halide_/PyEnums.cpp
  src/CodeGen_X86.cpp
  src/Target.cpp
  src/Target.h
  src/runtime/HalideRuntime.h
  src/runtime/x86_cpu_features.cpp
  test/correctness/simd_op_check_x86.cpp
Labels: dev_meeting

#8631 Fix top LLVM: renamed NVPTX barrier intrinsics.
  src/CodeGen_PTX_Dev.cpp
  src/runtime/ptx_dev.ll
Labels: build

#8634 Constrain Clang and LLD searches to LLVM version
  CMakePresets.json
  cmake/FindHalide_LLVM.cmake
Labels: build

#8595 Math functions renaming table for GPU backends to support vectorized evaluation of math functions.
  src/CodeGen_C.cpp
  src/CodeGen_C.h
  src/CodeGen_D3D12Compute_Dev.cpp
  src/CodeGen_GPU_Dev.cpp
  src/CodeGen_GPU_Dev.h
  src/CodeGen_Metal_Dev.cpp
  src/CodeGen_OpenCL_Dev.cpp
  src/CodeGen_Vulkan_Dev.cpp
  src/CodeGen_WebGPU_Dev.cpp
  src/runtime/opencl.cpp
  test/correctness/boundary_conditions.cpp
  test/correctness/math.cpp
Labels: code_cleanup, gpu
